/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static java.nio.file.Files.size;
import static java.util.Objects.hash;
import javafx.scene.chart.PieChart.Data;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agustina Mufidatuzzainiya_210605110144
 */
public class mainscreen extends javax.swing.JFrame {

    public methode data;
    public int sizeTable;
    DefaultTableModel model;
    public Object[] objek;
    public int nomor;
    String[] tabHeader = new String[]
    {"No", "Nama", "No Rumah", "No KK","No Hp", "Jumlah Anggota"};
    
    public mainscreen(int size) {
        //initComponents();
        this.sizeTable = size;
        initComponents();
        this.setLocationRelativeTo(null);
        model = new DefaultTableModel(tabHeader,0);
        data = new methode(sizeTable);
        objek = new Object[100];
        TableData.setModel(model);
        this.nomor = 0;
    }
    
    private mainscreen() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        insert = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDataWarga = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNoUrut = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoKK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNoRumah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoHP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtJmlAnggota = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        appearance = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnShow = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();
        btnSorting = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        insert.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("*Masukkan Banyak Data Masyarakat Terlebih Dahulu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtDataWarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataWargaActionPerformed(evt);
            }
        });
        jPanel2.add(txtDataWarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 20));

        btnSave.setText("SAVE");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel4.setText("NOMOR URUT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtNoUrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoUrutActionPerformed(evt);
            }
        });
        jPanel2.add(txtNoUrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 30));

        jLabel5.setText("NAMA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, -1, 10));
        jPanel2.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 230, 30));

        jLabel6.setText("NO. KARTU KELUARGA");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel2.add(txtNoKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 30));

        jLabel7.setText("NO. RUMAH");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));
        jPanel2.add(txtNoRumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 240, 30));

        jLabel8.setText("NO. HP");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));
        jPanel2.add(txtNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 240, 30));

        jLabel9.setText("JUMLAH ANGGOTA");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        jPanel2.add(txtJmlAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 240, 30));

        btnClear.setText("CLEAR");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        btnInsert.setText("INSERT");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg panel.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 700, 520));

        insert.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        jTabbedPane1.addTab("Insert", insert);

        appearance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "No KK", "No Rumah", "No HP", "Jumlah Anggota"
            }
        ));
        jScrollPane1.setViewportView(TableData);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 620, 170));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama", "No. Rumah", "No. KK", "Jumlah Anggota" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 150, 30));

        btnShow.setText("SHOW");
        btnShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowMouseClicked(evt);
            }
        });
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel3.add(btnShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        btnDeleteAll.setText("DELETE ALL");
        btnDeleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteAllMouseClicked(evt);
            }
        });
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });
        jPanel3.add(btnDeleteAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        btnSorting.setText("SORTING");
        btnSorting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSortingMouseClicked(evt);
            }
        });
        btnSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingActionPerformed(evt);
            }
        });
        jPanel3.add(btnSorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 190, 30));

        btnSearch.setText("SEARCH");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg panel.png"))); // NOI18N
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -170, 720, 520));

        appearance.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        jTabbedPane1.addTab("Appearance", appearance);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg frame.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jTabbedPane1))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataWargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataWargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataWargaActionPerformed

    private void txtNoUrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoUrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoUrutActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        String nama = txtnama.getText();
        int noRumah = Integer.parseInt(txtNoRumah.getText());
        int noKK = Integer.parseInt(txtNoKK.getText());
        String noTelp = txtNoHP.getText();
        int jumlah = Integer.parseInt(txtJmlAnggota.getText());
        int urut = Integer.parseInt(txtNoUrut.getText());
        
        
        data.insert(nama, noRumah, noKK, noTelp, jumlah, urut);        
        JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan");
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clearForm();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        int size  = Integer.parseInt(txtDataWarga.getText());
        mainscreen data = new mainscreen(size);
        JOptionPane.showMessageDialog(null, "Data Telah Tersimpan");
        data.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMouseClicked
        Show();
    }//GEN-LAST:event_btnShowMouseClicked

    private void btnDeleteAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAllMouseClicked
        data.DeleteAll();
    }//GEN-LAST:event_btnDeleteAllMouseClicked

    private void btnSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingActionPerformed
        String valueCombo = jComboBox1.getSelectedItem().toString();
        if(valueCombo.equals("Nama")){
            data.quickSortNama();
            Show();
            
        } else if(valueCombo.equals("No. Rumah")){
            data.BubbleSortNoRumah();
            Show();
        } else if(valueCombo.equals("No. KK")){
           data.BubbleSortNoKK();
            Show();
        }
        else if(valueCombo.equals("Jumlah Anggota")) {
            data.BubbleSortJmlAnggota();
            Show();
        }else{
           JOptionPane.showMessageDialog(null, "Data tidak dapat di urutkan");
        }
    }//GEN-LAST:event_btnSortingActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String search = txtSearch.getText();
        int hasil = data.binarySearch(search);    
        model.setRowCount(0);
        Object[]objek = {hasil, data.hashArray[hasil].nama, data.hashArray[hasil].noRumah, 
        data.hashArray[hasil].noKK, data.hashArray[hasil].noTelp, data.hashArray[hasil].jumlah};
        model.addRow(objek);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        Show();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSortingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortingMouseClicked
        Show();
    }//GEN-LAST:event_btnSortingMouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void clearForm() {
        txtNoUrut.setText("");
        txtnama.setText("");
        txtNoRumah.setText("");
        txtNoKK.setText("");
        txtNoHP.setText("");
        txtJmlAnggota.setText("");
    }
    
    private void Show() {
        model.setRowCount(0);
        for(int i=0; i<data.size; i++) {
            if(data.hashArray[i] == null) {
                data.hashArray[i] = null;
            }
            else {
                Object[]objek = {i, data.hashArray[i].nama, data.hashArray[i].noRumah, 
                data.hashArray[i].noKK, data.hashArray[i].noTelp,data.hashArray[i].jumlah};
                model.addRow(objek);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableData;
    private javax.swing.JPanel appearance;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnSorting;
    private javax.swing.JPanel insert;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDataWarga;
    private javax.swing.JTextField txtJmlAnggota;
    private javax.swing.JTextField txtNoHP;
    private javax.swing.JTextField txtNoKK;
    private javax.swing.JTextField txtNoRumah;
    private javax.swing.JTextField txtNoUrut;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables

//    private int hashFunc(int key) {
//        System.out.print("Enter key value to find: ");
//        key = Integer.parseInt(txtSearch.getText());
//        data = hash.find(key);
//        if (data != null) {
//            JOptionPane.showMessageDialog(null, "Nama\t\t:" + data.getNama() + "\n" + "Nama\t\t: " + data.getNoKK() + "\n" + "Alamat\t\t: " 
//                    + data.getAlamat() + "\n" + "Nomor HP\t\t: " + data.getHp(),
//                    "ID CARD", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            System.out.println("Couldn't find: " + key);
//        }
//    }

}
