
import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Putri Oktavia
 */
public class Antrian extends javax.swing.JFrame {

    /**
     * Creates new form Antrian
     */
    Queue<String> waitingqueue = new LinkedList<>();
    int no = 0;

    public Antrian() {
        initComponents();
        Mulai();
    }

    public void Mulai() {
        jljumlahantrian.setText("Jumlah Antrian");
        jltotalantrian.setText("Total Antrian");
        jlpanggilanantrian.setText("Nomor Panggilan Antrian");

        jltext1.setText("Mohon Untuk Segera Ke Loket");
        jltext2.setText("Dan Melakukan Pembayan");
        jltext3.setText("Terima Kasih Telah Melakukan Pemesan Tiket");
        jltext4.setText("--------------------");
        jltext5.setText("Sampai Jumpa");
        jltext6.setText("Silahkan Menunggu");
    }

    private void Ambil_Antrian() {
        no++;
        String antrian = "Nomor Antrian " + no;
        waitingqueue.add(antrian);
        String ukuran = String.valueOf(waitingqueue.size());
        jljumlahantrian.setText("Jumlah Antrian \n " + " " + ukuran);
        jlpanggilanantrian.setText("" + waitingqueue.peek());
        jltotalantrian.setText("Total Antrian " + " " + no);
        txtantrian.append("\n" + antrian);

        jltext1.setText("Mohon Untuk Segera Ke Loket");
        jltext2.setText("Dan Melakukan Pembayan");
        jltext3.setText("Terima Kasih Telah Melakukan Pemesan Tiket");
        jltext4.setText("--------------------");
        jltext5.setText("Sampai Jumpa");
        jltext6.setText("Silahkan Menunggu" + ukuran + "Antrian Lagi");
    }

    private void Proses_Antrian() {
        if (waitingqueue.isEmpty()) { //Jika antrian kosong
            JOptionPane.showMessageDialog(this, "Tolong ambil nomor antrian terlebih dahulu!");
        }
        txtantrian.setText("");
        waitingqueue.poll();//mengeluarkan head pada antrian dan memberikan nilai berupa item yang dikeluarkan 
        waitingqueue.forEach((Object element) -> { //perulangan pada proses antrian 
            txtantrian.append(element + "\n"); //menampilkan nilai antrian 
        });
        if (waitingqueue.isEmpty()) {
            jlpanggilanantrian.setText("------");
            String ukuran = String.valueOf(waitingqueue.size());//Pengembalian antrian
            jljumlahantrian.setText("Jumlah Antrian \n " + " " + ukuran);
            jltext6.setText("Silahkan Menunggu " + ukuran + " Antrian Lagi");
        } else {
            String ukuran = String.valueOf(waitingqueue.size());
            jljumlahantrian.setText("Jumlah Antrian \n " + " " + ukuran);
            jltext6.setText("Silahkan Menunggu " + ukuran + " Antrian Lagi");
            jlpanggilanantrian.setText("" + waitingqueue.peek()); //Melihat item yang berada pada head tanpa mengeluarkan dari queue
        }
    }

    private void out() {
        if (JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan keluar", "Terima Kasih", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jltotalantrian = new javax.swing.JLabel();
        jlpanggilanantrian = new javax.swing.JLabel();
        jbproses = new javax.swing.JButton();
        jbambil = new javax.swing.JButton();
        jljumlahantrian = new javax.swing.JLabel();
        jbout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtantrian = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jltext1 = new javax.swing.JLabel();
        jltext2 = new javax.swing.JLabel();
        jltext3 = new javax.swing.JLabel();
        jltext4 = new javax.swing.JLabel();
        jltext5 = new javax.swing.JLabel();
        jltext6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jltotalantrian.setAutoscrolls(true);
        jltotalantrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jltotalantrian);
        jltotalantrian.setBounds(290, 240, 160, 50);

        jlpanggilanantrian.setAutoscrolls(true);
        jlpanggilanantrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jlpanggilanantrian);
        jlpanggilanantrian.setBounds(550, 130, 160, 50);

        jbproses.setText("Proses Antrian");
        jbproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbprosesActionPerformed(evt);
            }
        });
        getContentPane().add(jbproses);
        jbproses.setBounds(320, 300, 110, 30);

        jbambil.setText("Ambil Antrian");
        jbambil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbambilActionPerformed(evt);
            }
        });
        getContentPane().add(jbambil);
        jbambil.setBounds(320, 340, 110, 30);

        jljumlahantrian.setAutoscrolls(true);
        jljumlahantrian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jljumlahantrian);
        jljumlahantrian.setBounds(290, 130, 160, 50);

        jbout.setText("Keluar");
        jbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboutActionPerformed(evt);
            }
        });
        getContentPane().add(jbout);
        jbout.setBounds(670, 480, 90, 30);

        txtantrian.setColumns(20);
        txtantrian.setRows(5);
        jScrollPane1.setViewportView(txtantrian);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 170, 220);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nomor Panggilan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(560, 100, 140, 30);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Daftar Antrian");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 100, 140, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ambil Antrian");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 100, 140, 30);

        jltext1.setForeground(new java.awt.Color(255, 255, 255));
        jltext1.setText("1");
        getContentPane().add(jltext1);
        jltext1.setBounds(550, 200, 180, 30);

        jltext2.setForeground(new java.awt.Color(255, 255, 255));
        jltext2.setText("2");
        getContentPane().add(jltext2);
        jltext2.setBounds(550, 230, 180, 30);

        jltext3.setForeground(new java.awt.Color(255, 255, 255));
        jltext3.setText("3");
        getContentPane().add(jltext3);
        jltext3.setBounds(550, 260, 180, 30);

        jltext4.setForeground(new java.awt.Color(255, 255, 255));
        jltext4.setText("4");
        getContentPane().add(jltext4);
        jltext4.setBounds(550, 290, 180, 30);

        jltext5.setForeground(new java.awt.Color(255, 255, 255));
        jltext5.setText("5");
        getContentPane().add(jltext5);
        jltext5.setBounds(550, 320, 180, 30);

        jltext6.setForeground(new java.awt.Color(255, 255, 255));
        jltext6.setText("6");
        getContentPane().add(jltext6);
        jltext6.setBounds(290, 200, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Antrian.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbprosesActionPerformed
        // TODO add your handling code here:
        Proses_Antrian();
    }//GEN-LAST:event_jbprosesActionPerformed

    private void jbambilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbambilActionPerformed
        // TODO add your handling code here:
        Ambil_Antrian();
    }//GEN-LAST:event_jbambilActionPerformed

    private void jboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboutActionPerformed
        // TODO add your handling code here:
        out();
    }//GEN-LAST:event_jboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbambil;
    private javax.swing.JButton jbout;
    private javax.swing.JButton jbproses;
    private javax.swing.JLabel jljumlahantrian;
    private javax.swing.JLabel jlpanggilanantrian;
    private javax.swing.JLabel jltext1;
    private javax.swing.JLabel jltext2;
    private javax.swing.JLabel jltext3;
    private javax.swing.JLabel jltext4;
    private javax.swing.JLabel jltext5;
    private javax.swing.JLabel jltext6;
    private javax.swing.JLabel jltotalantrian;
    private javax.swing.JTextArea txtantrian;
    // End of variables declaration//GEN-END:variables
}
