/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Putri Oktavia
 */
public class Daftar_Wisata extends javax.swing.JFrame {
    
    /**
     * Creates new form Daftar_Wisata
     */
    public Daftar_Wisata() {
        initComponents();  
   setLocationRelativeTo(this);
    setSize(775, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlnama = new javax.swing.JLabel();
        jbjtp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbjodip = new javax.swing.JButton();
        jbalun = new javax.swing.JButton();
        jbmuseum = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jlnama);
        jlnama.setBounds(350, 110, 31, 13);

        jbjtp.setText("Jatim Park");
        jbjtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjtpActionPerformed(evt);
            }
        });
        getContentPane().add(jbjtp);
        jbjtp.setBounds(180, 160, 100, 30);

        jButton1.setText("Pantai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 160, 100, 30);

        jbjodip.setText("Jodipan");
        jbjodip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjodipActionPerformed(evt);
            }
        });
        getContentPane().add(jbjodip);
        jbjodip.setBounds(230, 240, 90, 30);

        jbalun.setText("Alun-Alun");
        jbalun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbalunActionPerformed(evt);
            }
        });
        getContentPane().add(jbalun);
        jbalun.setBounds(500, 160, 80, 30);

        jbmuseum.setText("Museum");
        jbmuseum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmuseumActionPerformed(evt);
            }
        });
        getContentPane().add(jbmuseum);
        jbmuseum.setBounds(440, 240, 90, 30);

        jbback.setText("Back");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbback);
        jbback.setBounds(690, 370, 53, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/DaftarWisata.png"))); // NOI18N
        jLabel1.setText("ui");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                new Pantai().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbjodipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjodipActionPerformed
        // TODO add your handling code here:
                new Jodipan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbjodipActionPerformed

    private void jbmuseumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmuseumActionPerformed
        // TODO add your handling code here:
                new Museum().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbmuseumActionPerformed

    private void jbjtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjtpActionPerformed
        // TODO add your handling code here:
                new Jatim_Park().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbjtpActionPerformed

    private void jbalunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbalunActionPerformed
        // TODO add your handling code here:
                new Alun_Alun().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbalunActionPerformed

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        // TODO add your handling code here:
                new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbbackActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Wisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Wisata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbalun;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbjodip;
    private javax.swing.JButton jbjtp;
    private javax.swing.JButton jbmuseum;
    private javax.swing.JLabel jlnama;
    // End of variables declaration//GEN-END:variables

 


}
