/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Putri Oktavia
 */
public class Jatim_Park extends javax.swing.JFrame {

    /**
     * Creates new form Jatim_Park
     */
    public Jatim_Park() {
        initComponents();
    setLocationRelativeTo(this);
    setSize(775, 520);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbJTP1 = new javax.swing.JButton();
        jbJTP2 = new javax.swing.JButton();
        jbJTP3 = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbJTP1.setText("Jatim Park 3");
        jbJTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJTP1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbJTP1);
        jbJTP1.setBounds(100, 260, 110, 30);

        jbJTP2.setText("Jatim Park 1");
        jbJTP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJTP2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbJTP2);
        jbJTP2.setBounds(330, 260, 110, 30);

        jbJTP3.setText("Jatim Park 2");
        jbJTP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJTP3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbJTP3);
        jbJTP3.setBounds(560, 260, 110, 30);

        jbback.setText("Back");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbback);
        jbback.setBounds(670, 370, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/JatimPark.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbJTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJTP1ActionPerformed
        // TODO add your handling code here:
                new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbJTP1ActionPerformed

    private void jbJTP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJTP2ActionPerformed
        // TODO add your handling code here:
                new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbJTP2ActionPerformed

    private void jbJTP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJTP3ActionPerformed
        // TODO add your handling code here:
                new Order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbJTP3ActionPerformed

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        // TODO add your handling code here:
                new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jatim_Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jatim_Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jatim_Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jatim_Park.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jatim_Park().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbJTP1;
    private javax.swing.JButton jbJTP2;
    private javax.swing.JButton jbJTP3;
    private javax.swing.JButton jbback;
    // End of variables declaration//GEN-END:variables
}
