/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Putri Oktavia
 */
public class Jodipan extends javax.swing.JFrame {

    /**
     * Creates new form Jodipan
     */
    public Jodipan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbwarna = new javax.swing.JButton();
        jb3D = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbwarna.setText("Kampung Warna Warni");
        jbwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbwarnaActionPerformed(evt);
            }
        });
        getContentPane().add(jbwarna);
        jbwarna.setBounds(161, 270, 170, 30);

        jb3D.setText("Kampung Tridi");
        jb3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3DActionPerformed(evt);
            }
        });
        getContentPane().add(jb3D);
        jb3D.setBounds(470, 270, 170, 30);

        jbback.setText("Back");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbback);
        jbback.setBounds(690, 380, 53, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Jodipan.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        // TODO add your handling code here:
            new Menu().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbbackActionPerformed

    private void jbwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbwarnaActionPerformed
        // TODO add your handling code here:
             new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbwarnaActionPerformed

    private void jb3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3DActionPerformed
        // TODO add your handling code here:
            new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jb3DActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jodipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jodipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jodipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jodipan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jodipan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb3D;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbwarna;
    // End of variables declaration//GEN-END:variables
}
