
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Putri Oktavia
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
        setLocationRelativeTo(this);
        this.setSize(775, 520);
    }

    public void Next() {
        if (jtnama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong!!");
        } else if (jtalamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Alamat Identitas tidak boleh kosong!!");
        } else if (jtemail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Email Identitas tidak boleh kosong!!");
        } else if (jthp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nomor Handphone tidak boleh kosong!!");
        } else if (jtnoiden.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No Identitas  tidak boleh kosong!!");
        } else {
            new Antrian().setVisible(true);

            this.dispose();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtnama = new javax.swing.JTextField();
        jtalamat = new javax.swing.JTextField();
        jthp = new javax.swing.JTextField();
        jtemail = new javax.swing.JTextField();
        jtnoiden = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbnext = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jtnama);
        jtnama.setBounds(370, 120, 230, 30);
        getContentPane().add(jtalamat);
        jtalamat.setBounds(370, 160, 230, 30);
        getContentPane().add(jthp);
        jthp.setBounds(370, 200, 230, 30);

        jtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtemailActionPerformed(evt);
            }
        });
        getContentPane().add(jtemail);
        jtemail.setBounds(370, 240, 230, 30);
        getContentPane().add(jtnoiden);
        jtnoiden.setBounds(370, 280, 230, 30);

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No Identitas :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 280, 110, 30);

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 120, 70, 30);

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 160, 70, 30);

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No Handphone :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 200, 130, 30);

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 240, 70, 30);

        jbnext.setText("Next");
        jbnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnextActionPerformed(evt);
            }
        });
        getContentPane().add(jbnext);
        jbnext.setBounds(680, 370, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Order.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtemailActionPerformed

    private void jbnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnextActionPerformed
        // TODO add your handling code here:
        Next();
    }//GEN-LAST:event_jbnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbnext;
    private javax.swing.JTextField jtalamat;
    private javax.swing.JTextField jtemail;
    private javax.swing.JTextField jthp;
    private javax.swing.JTextField jtnama;
    private javax.swing.JTextField jtnoiden;
    // End of variables declaration//GEN-END:variables
}
