/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Putri Oktavia
 */
public class Pantai extends javax.swing.JFrame {

    /**
     * Creates new form Pantai
     */
    public Pantai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbBlkm = new javax.swing.JButton();
        jb3warna = new javax.swing.JButton();
        jbasmara = new javax.swing.JButton();
        jbngliyep = new javax.swing.JButton();
        jbback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jbBlkm.setText("Balekambangan");
        jbBlkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBlkmActionPerformed(evt);
            }
        });
        getContentPane().add(jbBlkm);
        jbBlkm.setBounds(50, 240, 110, 30);

        jb3warna.setText("Tiga Warna");
        jb3warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3warnaActionPerformed(evt);
            }
        });
        getContentPane().add(jb3warna);
        jb3warna.setBounds(231, 240, 120, 30);

        jbasmara.setText("Teluk Asmara");
        jbasmara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbasmaraActionPerformed(evt);
            }
        });
        getContentPane().add(jbasmara);
        jbasmara.setBounds(420, 240, 120, 30);

        jbngliyep.setText("Ngliyep");
        jbngliyep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbngliyepActionPerformed(evt);
            }
        });
        getContentPane().add(jbngliyep);
        jbngliyep.setBounds(611, 241, 110, 30);

        jbback.setText("Back");
        jbback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbback);
        jbback.setBounds(680, 370, 53, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pantai.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBlkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBlkmActionPerformed
        // TODO add your handling code here:
            new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbBlkmActionPerformed

    private void jb3warnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3warnaActionPerformed
        // TODO add your handling code here:
            new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jb3warnaActionPerformed

    private void jbasmaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbasmaraActionPerformed
        // TODO add your handling code here:
            new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbasmaraActionPerformed

    private void jbngliyepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbngliyepActionPerformed
        // TODO add your handling code here:
            new Order().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbngliyepActionPerformed

    private void jbbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbackActionPerformed
        // TODO add your handling code here:
            new Menu().setVisible(true);
            dispose();
    }//GEN-LAST:event_jbbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb3warna;
    private javax.swing.JButton jbBlkm;
    private javax.swing.JButton jbasmara;
    private javax.swing.JButton jbback;
    private javax.swing.JButton jbngliyep;
    // End of variables declaration//GEN-END:variables
}
