/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramData;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author niya
 */
public class FormRegistrasi extends javax.swing.JFrame {
    Connection con = null;
    Statement st = null;
    
    /**
     * Creates new form FormRegistrasi
     */
    public FormRegistrasi() {
        initComponents();  
    }
    
    private void hapuslayar() {
        txtuser.setText("");
        txtpass.setText("");
        txtketikpassword.setText("");
        txtnama.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        txtketikpassword = new javax.swing.JPasswordField();
        txtnama = new javax.swing.JTextField();
        btnregistrasi = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 415));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome, Mahasantri MSAA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 10, 345, 31);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRESENSI JAMA'AH MAHASANTRI MSAA TAHUN 2021-2022");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(106, 49, 286, 14);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(53, 101, 77, 14);

        jPasswordField.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField.setText("Password");
        getContentPane().add(jPasswordField);
        jPasswordField.setBounds(53, 141, 77, 14);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ketik Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(53, 178, 77, 14);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(53, 215, 77, 14);

        txtuser.setBackground(new java.awt.Color(204, 204, 255));
        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser);
        txtuser.setBounds(163, 98, 190, 30);

        txtpass.setBackground(new java.awt.Color(204, 204, 255));
        txtpass.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtpass.setPreferredSize(new java.awt.Dimension(4, 18));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass);
        txtpass.setBounds(163, 138, 190, 30);

        txtketikpassword.setBackground(new java.awt.Color(204, 204, 255));
        txtketikpassword.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtketikpassword.setPreferredSize(new java.awt.Dimension(4, 18));
        txtketikpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtketikpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtketikpassword);
        txtketikpassword.setBounds(163, 175, 190, 30);

        txtnama.setBackground(new java.awt.Color(204, 204, 255));
        txtnama.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        txtnama.setAlignmentX(1.0F);
        txtnama.setAlignmentY(1.0F);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama);
        txtnama.setBounds(163, 212, 190, 30);

        btnregistrasi.setBackground(new java.awt.Color(255, 204, 204));
        btnregistrasi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnregistrasi.setText("Registrasi");
        btnregistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrasi);
        btnregistrasi.setBounds(87, 294, 93, 23);

        btnback.setBackground(new java.awt.Color(255, 204, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(339, 294, 61, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image20.png"))); // NOI18N
        jLabel7.setMaximumSize(new java.awt.Dimension(500, 415));
        jLabel7.setMinimumSize(new java.awt.Dimension(500, 415));
        jLabel7.setPreferredSize(new java.awt.Dimension(500, 415));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtketikpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtketikpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtketikpasswordActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btnregistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrasiActionPerformed
        // TODO add your handling code here:
        try {
            if (txtuser.getText().equals("")||txtpass.getPassword().equals("")||
                    txtnama.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!", "Pesan", JOptionPane.ERROR_MESSAGE);
                hapuslayar();
            }else {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3308/form_uas","root","");
                st = con.createStatement();
                String simpan = "INSERT INTO fr_login values('" + txtuser.getText() + "',"
                        + "'" + String.valueOf(txtpass.getPassword()) + "','" + txtnama.getText() + "')";
                st = con.createStatement();
                int SA = st.executeUpdate(simpan);
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil");
                this.setVisible(false);
                new FormLogin().setVisible(true);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Akun sudah ada!", 
                    "Pesan", JOptionPane.WARNING_MESSAGE);
            hapuslayar();
        }
    }//GEN-LAST:event_btnregistrasiActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jPasswordField;
    private javax.swing.JPasswordField txtketikpassword;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
