/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales_program;

import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author JE_SOO
 */

public class add_database extends javax.swing.JFrame {
int movex;
int movey;
    /**
     * Creates new form add_database
     */
    public add_database() {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
        initComponents();
        setBackground(new Color(0,0,0,0));
        jPanel1.setEnabled(false);
        jPanel1.setVisible(false);
        
        listed();
    }
    
public void listed()
{
    DefaultTableModel table = new DefaultTableModel();
    
    table.addColumn("NO");
    table.addColumn("CODE ITEM");
    table.addColumn("NAME ITEM");
    table.addColumn("PRICE");
    table.addColumn("STOCK");
    
    try
    {
        Connection kon = conectionDB.koneksiDb();
        String sql = "SELECT `id`, `code`, `name`, `price`, `stock` FROM `produc`";
        Statement S = kon.createStatement();
        ResultSet R = S.executeQuery(sql);
        
        while(R.next()){
            table.addRow(new Object[]{
                R.getString(1),
                R.getString(2),
                R.getString(3),
                R.getString(4),
                R.getString(5),
            });
        }
        list.setModel(table);
    }catch(Exception e){
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        sto_i = new javax.swing.JTextField();
        pri_i = new javax.swing.JTextField();
        nam_i = new javax.swing.JTextField();
        co_i = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 30));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 7, 20, 20));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 53, 125, 30));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 53, 125, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jScrollPane1.setOpaque(false);

        list.setAutoCreateRowSorter(true);
        list.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "CODE ITEM", "NAME ITEM", "PRICE", "STOCK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        list.setGridColor(new java.awt.Color(204, 204, 204));
        list.setSelectionBackground(new java.awt.Color(51, 51, 51));
        list.getTableHeader().setResizingAllowed(false);
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 530, 345));

        sto_i.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        sto_i.setBorder(null);
        sto_i.setOpaque(false);
        getContentPane().add(sto_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 263, 200, 30));

        pri_i.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        pri_i.setBorder(null);
        pri_i.setOpaque(false);
        getContentPane().add(pri_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 263, 200, 30));

        nam_i.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        nam_i.setBorder(null);
        nam_i.setOpaque(false);
        getContentPane().add(nam_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 190, 200, 30));

        co_i.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        co_i.setBorder(null);
        co_i.setOpaque(false);
        getContentPane().add(co_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 190, 200, 30));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 375, 119, 32));

        con.setText("jLabel7");
        con.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conMouseClicked(evt);
            }
        });
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales_program/images/Database.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        setSize(new java.awt.Dimension(740, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int dragx = evt.getXOnScreen();
        int gragy = evt.getYOnScreen();
        
        this.setLocation(dragx - movex, gragy - movey);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        movex = evt.getX();
        movey = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0;i=i+0.5)
        {
            String val= i + "F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(5);
            } catch (InterruptedException ex) {
                
            }
        }
        System.out.println(evt);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        for(double i=1.0; i<=0.0;i=i-0.5)
        {
            String val= i + "F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(5);
            } catch (InterruptedException ex) {
                
            }
        }
        System.out.println(evt);
    }//GEN-LAST:event_formWindowClosed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ImageIcon A = new ImageIcon(getClass().getResource("/sales_program/images/SAVE1.png"));
        jLabel4.setIcon(A);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ImageIcon A = new ImageIcon(getClass().getResource(""));
        jLabel4.setIcon(A);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        ImageIcon A = new ImageIcon(getClass().getResource("/sales_program/images/Database1.png"));
        jLabel1.setIcon(A);
        
        jPanel1.setEnabled(true);
        jPanel1.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        ImageIcon A = new ImageIcon(getClass().getResource("/sales_program/images/Database.png"));
        jLabel1.setIcon(A);
        
        jPanel1.setEnabled(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection kon = conectionDB.koneksiDb();
        try
        {
            String sql = "INSERT INTO `produc`(`code`, `name`, `price`, `stock`) VALUES ('"+co_i.getText()+"','"+nam_i.getText()+"','"+pri_i.getText()+"','"+sto_i.getText()+"')";
        
            
            
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conMouseClicked
        try
        {
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(program.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_conMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_database.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_database().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField co_i;
    private javax.swing.JLabel con;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable list;
    private javax.swing.JTextField nam_i;
    private javax.swing.JTextField pri_i;
    private javax.swing.JTextField sto_i;
    // End of variables declaration//GEN-END:variables
}
