/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sales_program;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.URLDataSource;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JE_SOO
 */
public class program extends javax.swing.JFrame {

    int x;
    int y;
    
    public program() {
        initComponents();
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
        
        setBackground(new Color(0,0,0,0));
        jPanel1.setEnabled(false);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        log_out = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        trans = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales_program/images/1.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 9, 16, 16));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales_program/images/1.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 9, 16, 16));

        mc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mcMouseDragged(evt);
            }
        });
        mc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mcMousePressed(evt);
            }
        });
        getContentPane().add(mc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        log_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_outMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_outMouseExited(evt);
            }
        });
        jPanel1.add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 130, 20));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closeMouseReleased(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 130, 20));

        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });
        jPanel1.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 20));

        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        jPanel1.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, 20));

        trans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transMouseExited(evt);
            }
        });
        jPanel1.add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales_program/men.png"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 104));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 34, 130, 104));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 80, 20));

        con.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conMouseClicked(evt);
            }
        });
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sales_program/bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        setSize(new java.awt.Dimension(740, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mcMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMouseDragged
        int mousex = evt.getXOnScreen();
        int mousey = evt.getYOnScreen();
        
        this.setLocation(mousex - x, mousey - y);
    }//GEN-LAST:event_mcMouseDragged

    private void mcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_mcMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/2.png"));
        jLabel4.setIcon(AS);
    
        jLabel4.setVisible(true);
        jLabel4.setEnabled(true);
        jLabel2.setVisible(false);
        jLabel2.setEnabled(false);
        jPanel1.setEnabled(true);
        jPanel1.setVisible(true);
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/1.png"));
        jLabel2.setIcon(AS);
        
        
        jLabel2.setEnabled(true);
        jLabel2.setVisible(true);
        jLabel4.setVisible(false);
        jLabel4.setEnabled(false);
        jPanel1.setEnabled(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel4MousePressed

    private void transMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseEntered
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/aa.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_transMouseEntered

    private void transMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transMouseExited
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_transMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/bb.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_aboutMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/cc.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_helpMouseEntered

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_helpMouseExited

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/dd.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_closeMouseExited

    private void log_outMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseEntered
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/ee.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_log_outMouseEntered

    private void log_outMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_outMouseExited
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_log_outMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/images/dd.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_closeMousePressed

    private void closeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseReleased
        ImageIcon AS = new ImageIcon(getClass().getResource("/sales_program/men.png"));
        menu.setIcon(AS);
    }//GEN-LAST:event_closeMouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        
            Connection A = conectionDB.koneksiDb();
            if(A!=null){
              new add_database().setVisible(true);  
            }
            else{
                JOptionPane.showMessageDialog(null, "Connection Error !");
            }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conMouseClicked
        try{
            Desktop.getDesktop().open(new File("C:\\xampp\\xampp-control.exe"));
        } catch (IOException ex) {
            Logger.getLogger(program.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_conMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel close;
    private javax.swing.JLabel con;
    private javax.swing.JLabel help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel log_out;
    private javax.swing.JLabel mc;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel trans;
    // End of variables declaration//GEN-END:variables
}
